# 08.예외처리

#TIL/java/자바의정석

---

## 1. 예외처리

### 프로그램 오류

- 컴파일 에러: 컴파일 시에 발생하는 에러
- 런타임 에러: 실행 시에 발생하는 에러
- 논리적 에러: 실행은 되지만, 의도와 다르게 동작하는 경우

<br>

자바에서는 실행 시(runtime) 발생할 수 있는 프로그램 오류를 '에러(error)'와 '예외(exception)', 두 가지로 구분하였다.

- 에러(error) : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류 / 메모리 부족(OutOfMemoryError), 스택오버플로우(StackOverflowError) 등
- 예외(exception) : 프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류

---

### 예외 클래스의 계층 구조

Exception과 Error 역시 클래스로 정의되어 있으며 Object 클래스의 자손들이다.

모든 예외의 최고 조상은 Exception 클래스이다.

<br>

Exception

- IOException
- ClassNotFoundException
- ...
- RuntimeException
  - ArithmeticException (정수를 0으로 나누기 시도)
  - ClassCastException (클래스간의 잘못된 형변환 시도)
  - NullPointerException (값이 null인 참조변수의 멤버를 호출)
  - IndexOutOfBoundsException (배열의 범위를 벗어남)
  - ...

<br>

위와 같이 예외 클래스들은 두 그룹으로 나눌 수 있다.

1. Exception 클래스와 그 자손들 (RuntimeException과 자손들 제외) - CheckedException
2. RuntimeException 클래스와 그 자손들 - UncheckedException

<br>

- Exception 클래스들 - 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
- RuntimeException 클래스들 - 프로그래머의 실수로 발생하는 예외

---

### 예외 처리 / try-catch문

예외처리 (exception handling)

정의: 프로그램 실행 시 발생할 수 있는 예외에 대비한 코드를 작성하는 것

목적: 프로그램의 비정상 종료를 막고, 정상적인 실행 상태를 유지하는 것

<br>

```java
try {
  // 예외가 발생할 가능성이 있는 문장들
} catch (Exception1 e1) {
	// Exception1이 발생했을 경우, 이를 처리하기 위한 문장
} catch (Exception2 e2) {
	// Exception2가 발생했을 경우, 이를 처리하기 위한 문장
} catch (Exception3 e3) {
	// Exception3이 발생했을 경우, 이를 처리하기 위한 문장
}
```

발생한 예외의 종류와 일치하는 단 한개의 catch 블럭만 수행 (일치하는 catch 블럭이 없을 경우 예외가 처리되지 않는다.)

---

### printStackTrace() 와 getMessage()

예외 발생 시 생성되는 예외 클래스의 인스턴스에는 발생한 예외에 대한 정보가 담겨 있으며, getMessage()와 printStackTrace()를 통해 이러한 정보를 얻을 수 있다.

- printStackTrace() : 예외 발생 당시의 호출스택 (Call Stack)에 있었던 메서드의 정보와 예외 메시지를 화면에 출력한다.
- getMessage() : 발생한 예외 클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

```java
try {
			System.out.println(3);
			System.out.println(0 / 0);
			System.out.println(4); // 실행되지 않는다.
		} catch (ArithmeticException ae) {
			ae.printStackTrace();
			System.out.println("예외 메시지: " + ae.getMessage());
			System.out.println(6);
		}
```

---

### 예외 발생시키기

throw를 사용해서 프로그래머가 고의로 예외를 발생시킬 수 있다.

1. 먼저, 연산자 new를 이용해서 발생시키려는 예외 클래스의 객체를 만든다.
   - Exception e = new Exception("고의로 발생시켰음");
2. 키워드 throw를 이용해서 예외를 발생시킨다.
   - throw e;

한줄로 줄이면 throw new Exception("고의로 발생시켰음");

> Exception 인스턴스를 생성할 때, 생성자에 문자열을 넣어주면 Exception 인스턴스에 메시지로 저장된다. (getMessage()를 통해 얻을 수 있다.)

<br>

컴파일러가 예외처리를 확인하지 않는 RuntimeException 클래스들은 'unchecked 예외'라고 부르고, 예외처리를 확인하는 Exception 클래스들은 'checked 예외'라고 부른다.

---

### 메서드에 예외 선언하기

메서드에 예외를 선언하기 위해서는 메서드의 선언부에 키워드 throws를 사용해서 메서드 내에서 발생할 수 있는 예외를 적어준다.

예외가 여러 개일 경우에는 쉼표로 구분한다.

```java
void method() throws Exception1, Exception2, ... Exception N {
	// 메서드의 내용
}
```

> 예외를 발생시키는 키워드 throw와 예외를 메서드에 선언할 때 쓰이는 throws를 잘 구별하자.

<br>

자바에서는 메서드를 작성할 때 메서드 내에서 발생할 가능성이 있는 예외를 메서드의 선언부에 명시하여 이 메서드를 사용하는 쪽에서는 이에 대한 처리를 하도록 강요한다. (어떤 예외가 발생할 것인지에 대해 고려해야하는 프로그래머의 짐을 덜어주고 견고한 프로그램 코드를 작성할 수 있게 도와준다.)

<br>

## finally 블럭

finally 블럭은 예외의 발생여부에 상관없이 실행되어야할 코드를 포함시킬 목적으로 사용된다.

<br>

```java
try {
  // 예외가 발생할 가능성이 있는 문장들
} catch (Exception1 e1) {
	// 예외 처리를 위한 문장
} finally {
  // 예외의 발생여부에 관계없이 항상 수행되어야하는 문장들
}
```

<br>

try 블럭에서 return문이 실행되는 경우에도 finally 블럭의 문장들은 실행된 후에, 실행 중인 메서드를 종료한다.

<br>

## 자동 자원 반환 try - with - resources문





















